Adgangsstyring Symfony bundle
itk-dev/azure-ad-delta-sync-bundle pull request #7
Opened 2021-08-05 09:11 UTC by jekuaitk

Symfony bundle for https://github.com/itk-dev/adgangsstyring

2021-08-09 07:12 UTC, turegjorup requested changes
The name is just wrong. But I really like that we are building reusable components. Also really like that we have a test setup even if it could be expanded. Then there are a "few" comments to the actual implementation 😄

2021-08-09 07:12 UTC, turegjorup commented on .github/workflows/pr.yaml
> +          php-version: 7.4
Should be a matrix, `php: [ '7.4', '8.0' ]`, also the composer option should be covered by matrix `dependency-version: [ prefer-lowest, prefer-stable ]`

2021-08-09 07:12 UTC, turegjorup commented on .github/workflows/pr.yaml
> +          extensions: ctype, dom, iconv, json, zip, gd, soap
Are these needed? I get json but the rest?

2021-08-09 07:12 UTC, turegjorup commented on .github/workflows/pr.yaml
> +          composer validate composer.json
Please use `--strict`

2021-08-09 07:12 UTC, turegjorup commented on .github/workflows/pr.yaml
> +          composer validate composer.json
Also actually doing an install to ensure dependencies resolves is a good idea.
`composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction`

2021-08-09 07:12 UTC, turegjorup commented on README.md
> +# Adgangsstyring Bundle
Why the name "Adgangsstyring" - It's not what it does, and we don't name things in danish?

I know it wraps https://github.com/itk-dev/adgangsstyring but this is also badly and wrongly named.

2021-08-09 07:12 UTC, turegjorup commented on README.md
> +Symfony bundle for user access control via Azure AD.
It doesn't do "access control". It does enables the removal of users no longer found in the AD.

2021-08-09 07:12 UTC, turegjorup commented on README.md
> +akin may be among the users the bundle provides.
... The using system should implement logic to ensure these users are not deleted unintentionally.

2021-08-09 07:12 UTC, turegjorup commented on README.md
> +### Unit Testing
Where is the docker setup?

2021-08-09 07:12 UTC, turegjorup commented on README.md
> +If you wish to run the coding standard tests for Markdown files
This is covered under development setup and can be removed

2021-08-09 07:12 UTC, turegjorup commented on README.md
> +Note that `user_property` and `user_claim_property`
Please explain `user_property` and `user_claim_property`. What are they, what are they used for, what does it mean for them to "match up"?

2021-08-09 07:12 UTC, turegjorup commented on src/Command/AccessControlCommand.php
> +        parent::__construct($name);
None of the above arguments should be necessary for this command. Instead define the `UserHandler` and `Controller` as services and inject them in the command. Also see comment below under the `execute()` method

2021-08-09 07:12 UTC, turegjorup commented on src/Command/AccessControlCommand.php
> +        $handler = new UserHandler($this->dispatcher, $this->em, $this->user_class, $this->user_property, $this->user_claim_property);
In general, never do `New Something` when you're doing dependency injection. It's an anti pattern and a test smell. Only the DI container should be responsible for instantiating services. If you feel the need to do it like this, always stop and backtrack your design decisions. There will almost always be a better way of doing it.

Specifically the current implementation means that we will 
* have to duplicate code if you need to use `UserHandler` in a different service
* if we want to write tests for this command then there is no easy way to mock it's dependencies.

2021-08-09 07:12 UTC, turegjorup commented on src/Command/AccessControlCommand.php
> +        $client = new Client();
See above about `new`

2021-08-09 07:12 UTC, turegjorup commented on src/Command/AccessControlCommand.php
> +        $controller = new Controller($client, $this->options);
See above about `new`

2021-08-09 07:12 UTC, turegjorup commented on src/Command/AccessControlCommand.php
> +        return Command::SUCCESS;
This will not always work, so always returning `Command::SUCCESS` is a bit optimistic. Preferably you should wrap the command logic in a `try catch` in order to handle errors and exceptions

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +        $this->cache = new FilesystemAdapter();
Again, inject, don't do `new`. Also, always code to the interface, not the implementation. 

The using system can have legitimate reasons for using a different cache implementation, and there is no practical reason to lock this to the `FilesystemAdapter`. Instead use the `Symfony\Component\Cache\Adapter\AdapterInterface` or similar as type hint and make it part of the config what cache service to inject. See https://github.com/danskernesdigitalebibliotek/agency-auth-bundle/blob/develop/src/DependencyInjection/DanskernesDigitaleBibliotekAgencyAuthExtension.php for a way to do it.

Alternatively inject the symfony app cache service, as that is configurable on the framework level for the using system.

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +        $repository = $this->em->getRepository($this->user_class);
This dependency on Doctrine is not strictly necessary. I'll accept it because we always used Symfony and Doctrine together, but theoretically we could define an `UserStorageInterface` and then the using system could implement that interface relevant to the storage the system uses.

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +        $users = $repository->findAll();
This will fail in production. Never use `findAll()` in a situation where you can't know how many objects are returned, because you will face memory issues.

Use https://github.com/Ocramius/DoctrineBatchUtils to batch load users.

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +
Docblock missing

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +    /**
Docblock incomplete. What does this do?

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +    /**
Docblock incomplete. What does this do?

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +    /**
Docblock incomplete. What does this do?

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +        // Create PropertyAccessor
Comments that only describe what the code does are irrelevant.

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +        // setup cache
Comments that only describe what the code does are irrelevant. Instead describe why we need the cache. What is it used for in the implementation?

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +        // Array for users marked for potential removal
👍 for this comment

2021-08-09 07:12 UTC, turegjorup commented on src/Handler/UserHandler.php
> +                unset($systemUsersArray[$key]);
This can be a lot of searches over the `$systemUsersArray`. A potential optimization would be to use  `array_intersect()` similar to what we do here https://github.com/itk-dev/adgangsstyring_drupal/pull/3/files#diff-3f736b88ced6c5d238b807d7c49bb868ef05f583f0328687e8613c0d9872934fR142

2021-08-09 07:12 UTC, turegjorup commented on tests/UserHandlerTest.php
> +        $cache = new FilesystemAdapter();
You should mock the cache as well. That way you can also better assert that the cache is used correctly

2021-08-09 07:12 UTC, turegjorup commented on tests/UserHandlerTest.php
> +        $cache = new FilesystemAdapter();
AAgain - would prefer a mocked cache

2021-08-09 07:12 UTC, turegjorup commented on tests/UserHandlerTest.php
> +
Assert that `dispatch()` is called with correct argument/user list?

2021-08-09 07:12 UTC, turegjorup commented on src/Command/AccessControlCommand.php
> +        $controller->run($handler);
Because this depends on the cache for argument storage it will potentially have unknown side effects if the command is ever run twice in parallel. You should use a [lock](https://symfony.com/doc/current/lock.html#locking-a-resource) to ensure only one instance is running at a time

2021-08-18 12:04 UTC, jekuaitk commented on .github/workflows/pr.yaml
> +          extensions: ctype, dom, iconv, json, zip, gd, soap
Removed unnecessary extensions.

2021-08-30 08:18 UTC, jekuaitk commented on README.md
> +# Adgangsstyring Bundle
Renamed to `itk-dev/azure-ad-delta-sync-bundle`, Azure AD Delta Sync Symfony Bundle.

2021-08-30 08:18 UTC, jekuaitk commented on README.md
> +Symfony bundle for user access control via Azure AD.
Updated description

2021-08-30 08:20 UTC, jekuaitk commented on README.md
> +akin may be among the users the bundle provides.
Much better and clearer documentation. Updated

2021-08-30 08:21 UTC, jekuaitk commented on README.md
> +If you wish to run the coding standard tests for Markdown files
Removed unnecessary comment in documentation

2021-08-30 09:13 UTC, jekuaitk commented on README.md
> +Note that `user_property` and `user_claim_property`
Updated to be more clearer and telling - they should handle equivalent and unique properties eg. email

2021-08-30 12:19 UTC, jekuaitk commented on README.md
> +### Unit Testing
Added docker setup

2021-08-31 07:51 UTC, jekuaitk commented on src/Command/AccessControlCommand.php
> +        parent::__construct($name);
Defined `UserHandler` and `Controller` as services and dependency injected them. Very good point - looks cleaner and should make testing easier.

2021-08-31 07:52 UTC, jekuaitk commented on src/Command/AccessControlCommand.php
> +        $handler = new UserHandler($this->dispatcher, $this->em, $this->user_class, $this->user_property, $this->user_claim_property);
Declared as service and used dependency injection instead

2021-08-31 07:52 UTC, jekuaitk commented on src/Command/AccessControlCommand.php
> +        $client = new Client();
Used service and dependency method instead

2021-08-31 07:53 UTC, jekuaitk commented on src/Command/AccessControlCommand.php
> +        $controller = new Controller($client, $this->options);
Used service and dependency method instead

2021-08-31 07:56 UTC, jekuaitk commented on src/Command/AccessControlCommand.php
> +        return Command::SUCCESS;
Surrounded by `try catch`. Errors should be telling from `ItkDev\AzureAdDeltaSync\Controller`

2021-08-31 08:26 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +        $this->cache = new FilesystemAdapter();
Used `Symfony\Component\Cache\Adapter\AdapterInterface` as type hint and made cache pool configurable

2021-08-31 08:29 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +        $repository = $this->em->getRepository($this->user_class);
Good point, will keep it this way for now

2021-08-31 08:32 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +        $users = $repository->findAll();
Good point. We agreed that the systems we build in Symfony will not encounter this situation due to the amount of users

2021-08-31 08:55 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +
Added Docblock

2021-08-31 08:55 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +    /**
Added Docblock

2021-08-31 08:55 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +    /**
Added Docblock

2021-08-31 08:55 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +    /**
Added Docblock

2021-08-31 08:58 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +        // Create PropertyAccessor
Removed unnecessary comments

2021-08-31 10:11 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +                unset($systemUsersArray[$key]);
Nice catch, it will indeed search over `$systemUsersArray` for every user.

Adding to  `$azureUsersArray` instead and then computing `array_intersect` and `array_diff` after

2021-08-31 10:33 UTC, jekuaitk commented on src/Handler/UserHandler.php
> +        // setup cache
Removed unnecessary comments

2021-08-31 11:28 UTC, jekuaitk commented on src/Command/AccessControlCommand.php
> +        $controller->run($handler);
Used lock to ensure flow is only running one at a time

2021-08-31 12:11 UTC, jekuaitk commented on tests/UserHandlerTest.php
> +        $cache = new FilesystemAdapter();
Mocked cache for tests

2021-08-31 12:12 UTC, jekuaitk commented on tests/UserHandlerTest.php
> +        $cache = new FilesystemAdapter();
Mocked cache for tests

2021-08-31 12:13 UTC, jekuaitk commented on tests/UserHandlerTest.php
> +        $cache = new FilesystemAdapter();
Mocked cache for tests

2021-08-31 12:42 UTC, jekuaitk commented on tests/UserHandlerTest.php
> +
Added method for creating DeleteUserEvent `createDeleteUserEvent` to allow for asserting correct argument. Also added test for `createDeleteUserEvent` method

2021-08-31 12:48 UTC, jekuaitk commented on .github/workflows/pr.yaml
> +          composer validate composer.json
Added `--strict` and ensured dependencies install via `composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction`

2021-09-01 08:34 UTC, jekuaitk commented on .github/workflows/pr.yaml
> +          php-version: 7.4
Added `php-version` matrix and `dependency-version` matrix

2021-09-06 13:01 UTC, turegjorup approved these changes

2021-09-07 07:44 UTC, merged